version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: reliefflow-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reliefflow
      POSTGRES_USER: relief
      POSTGRES_PASSWORD: relief
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: reliefflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:


